---
os: linux
dist: xenial

services:
  - docker

language: generic

# Only execute travis in master, PR to master or tags
branches:
  only:
    - master

stages:
  - arm64
  - amd64

env:
  global:
    - secure: "Wk4qGYM6sgJgzNpFX1nyZzpc9XPFws6pSHB+RXw3Zm0UeyU/RAFnILcx+l+UZXqxfYOF4RI358v/cCWzCk7M5sBjQshyYYU/Jl326vQiRlHARLcA8ZteWzIUaal4BYkqcuoCaNYaR9qQkn3tZjNkmek0/rrphq/4DQO8ooppfzo7CvP1EqYAU92NX6NkHf4KqSSWypnjSO01nhqoYB6TSBRjcom9+pXcbRIkmKD+X705JlhWuKeIJrJoPHGdUTHvpVLtnR9eWuBDnL7UF3P1tV0ne6i0vLKGb0WVtgaU/+AA0WqHIIsSjkVsi4eCPzRl7U14w7w61LnibS662KF17Ql7qMFfd9bl4+srclgBfe8sxgEHO/+8z92Icjc/w96t61mmTyhwMJgdkzZ7jP55IqsyVjd8giV3X2iFZtoAxGP7VntmQ7TynWUuHb0wQg3Nhdcy9tfYmbwK4htba7Ryvw+2jHnEMpnbGUpxu0cQfbZaAeMGrvpQqwd/LbiJMCI+ZrLE71+To7+0/h//XLlGSnodNbBBAzo0ot9pVoohc7i+2HJ6TaHpOUJOhjcsMm/6YysR2n2UT4BB/HUyX43u4cU6Kl8xEu/7BrVz0O4frZ/WsZgwbZ6aX6QrvWDVnvJyz21iovTeCRvY9kCJTFH131thxcuXkaOB9YAw+RG+Mns="


jobs:
  include:
    - stage: arm64
      name: "build and push arm"
      arch: arm64
      script: bash deploy.sh
      env:
        # workaround arm64: https://travis-ci.community/t/error-occurs-when-deploy-to-github-release-you-dont-have-write-permissions-for-the-var-lib-gems-2-5-0-directory/5840
        - PATH=~/.ruby/bin:$PATH
        - GEM_HOME=~/.ruby
    - stage: amd64
      name: "build and push amd64 and manifest"
      script: bash deploy.sh
