---
os: linux
dist: xenial

services:
  - docker

language: generic

# Only execute travis in master, PR to master or tags
branches:
  only:
    - master

stages:
  - arm64
  - amd64


jobs:
  include:
    - stage: arm64
      name: "build and push arm"
      arch: arm64
      script: ./deploy.sh
      env:
        # workaround arm64: https://travis-ci.community/t/error-occurs-when-deploy-to-github-release-you-dont-have-write-permissions-for-the-var-lib-gems-2-5-0-directory/5840
        - PATH=~/.ruby/bin:$PATH
        - GEM_HOME=~/.ruby
        - DOCKER_USERNAME=pando85
    - stage: amd64
      name: "build and push amd64 and manifest"
      script: ./deploy.sh
      env:
        - DOCKER_USERNAME=pando85
